const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(process.env.TEST_HTML||'public/v2.html','utf8');
function node(tag='div'){return {tag,value:'',textContent:'',disabled:false,hidden:false,children:[],classList:{toggle(){},add(){}},setAttribute(){},append(...n){this.children.push(...n)},replaceChildren(){this.children=[]},querySelector(t){return this.children.find(n=>n.tag===t)},focus(){},click(){}}}
const nodes={},context={document:{getElementById:id=>nodes[id]??=node(),createElement:node,createTextNode:t=>t},window:{print(){},addEventListener(){},confirm(){return true}},URL,Blob,setTimeout,AbortController};nodes.language=node();nodes.language.value='zh';nodes.role=node();nodes.secondary=node();nodes.attachment=node();
vm.createContext(context);vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],context);const evaluate=s=>vm.runInContext(s,context);
assert.equal(evaluate('cats.length'),12);assert.equal(nodes.export.disabled,true);
assert.throws(()=>evaluate('createReport("review","",zhSample,"","")'));
nodes.role.value='buyer';evaluate('run()');assert.equal(nodes.findingCount.textContent,11);
const buyer=evaluate('state.report.items[2].impact[0]');nodes.role.value='seller';nodes.role.onchange();assert.equal(nodes.export.disabled,false);evaluate('run()');assert.notEqual(evaluate('state.report.items[2].impact[0]'),buyer);
evaluate('updateItem("P03","edited","我的测试修改<script>alert(1)</script>")');assert.equal(nodes.handledCount.textContent,1);assert(evaluate('reportText().includes("我的测试修改")'));
nodes.language.value='en';nodes.language.onchange();assert.equal(evaluate('state.report.items[2].status'),'edited');assert(evaluate('reportText().includes("User edit record")'));assert.equal(evaluate('draft(state.report.items[2])'),evaluate('state.report.items[2].direction[1]'));
nodes.language.value='zh';nodes.language.onchange();assert(evaluate('draft(state.report.items[2]).includes("我的测试修改")'));
assert.throws(()=>evaluate('updateItem("P03","edited","")'));
assert.throws(()=>evaluate('createReport("review","buyer",zhSample+"改动","","")'));
assert.throws(()=>evaluate('createReport("review","buyer",zhSample,"","附件")'));
assert.throws(()=>evaluate('createReport("review","buyer","","","")'));
evaluate('loadSample("en"); run()');assert(evaluate('state.report.items.every(f=>enSample.includes(f.quotes[0]))'));
evaluate('setMode("compare"); loadSample(); run()');assert.equal(nodes.findingCount.textContent,4);assert(evaluate('state.report.items.every(f=>pairZh.includes(f.quotes[0])&&pairEn.includes(f.quotes[1]))'));
evaluate('state.selected=2; render()');assert(evaluate('reportText().includes("D01")'));nodes.print.onclick();assert.equal(evaluate('state.selected'),2);
nodes.contract.value+='modified';nodes.contract.oninput();assert.equal(nodes.export.disabled,true);evaluate('run()');assert.equal(evaluate('state.report'),null);
assert(!/innerHTML|XMLHttpRequest|localStorage|<script[^>]*src=|<link[^>]*href=/.test(html));
if(!process.env.TEST_HTML)assert(!/fetch\(/.test(html));
console.log('PASS: 12 categories; both roles; ZH/EN samples and reports; 4 aligned differences; user edits and language retention; empty/custom/attachment guards; citation matching; report invalidation; full export; print-filter reset; no network or HTML injection. Browser/WebMCP not verified.');

evaluate('setMode("review"); loadSample(); run()');
evaluate('updateItem("P01","keep")');
assert.equal(evaluate('orderedItems(state.report.items)[0].id'),'P02');
assert.equal(evaluate('orderedItems(state.report.items).at(-1).id'),'P01');
evaluate('state.selected=1; updateItem("P02","reject")');
assert.equal(evaluate('state.selected'),2);
evaluate('updateItem("P02","pending")');
assert.equal(evaluate('orderedItems(state.report.items)[0].id'),'P02');
evaluate('state.selected=-1; state.report.items.forEach(f=>{if(f.status==="pending") updateItem(f.id,"keep")})');
assert.equal(evaluate('nextPending(state.report.items,"P12")'),undefined);
assert.equal(nodes.pendingCount.textContent,0);
assert(nodes.cards.children.some(n=>n.id==='completion'));
evaluate('updateItem("P01","pending")');
assert.equal(evaluate('orderedItems(state.report.items)[0].id'),'P01');
assert.equal(nodes.pendingCount.textContent,1);
evaluate('setMode("compare"); loadSample(); run(); updateItem("D01","edited","new")');
assert.equal(evaluate('orderedItems(state.report.items)[0].id'),'D02');
console.log('PASS: handled cards move to bottom; pending original order; category advances; reset restores; completion; bilingual workflow.');
evaluate('setMode("review"); loadSample(); run()');
assert.equal(nodes.categories.children.length,13);
nodes.categories.children[11].onclick();
assert.equal(evaluate('state.selected'),10);
assert.equal(nodes.cards.scrollTop,0);
evaluate('updateItem("P11","keep")');
assert.equal(evaluate('state.selected'),11);
assert.equal(nodes.categories.children.length,13);
assert(!html.includes('scrollIntoView'));
assert(!html.includes('不替用户选择地点'));
assert(!html.includes('不替双方编写规格'));
assert(!html.includes('不默认中文正确'));
assert(html.includes('.cards{position:relative;'));
console.log('PASS: category controls remain after action, category click resets only result scroll, internal instruction wording removed.');

evaluate('setMode("review"); loadSample()');
nodes.role.value='';nodes.role.onchange();
assert.equal(nodes.export.disabled,true);
const choices=nodes.cards.children[0].children.at(-1).children;
assert.equal(choices.length,2);
choices[0].onclick();
assert.equal(evaluate('state.report.role'),'buyer');
assert.equal(nodes.export.disabled,false);
nodes.role.value='seller';nodes.role.onchange();
assert.equal(evaluate('state.report.role'),'seller');
evaluate('loadSample("en")');
assert.equal(evaluate('state.report.source'),evaluate('enSample'));
evaluate('setMode("compare"); loadSample()');
assert.equal(nodes.categories.hidden,false);
assert.equal(nodes.categories.children.length,3);
evaluate('state.selected=-3; render()');
assert.equal(nodes.cards.children.filter(n=>n.tag==='article').length,0);
evaluate('state.selected=-2; render(); updateItem("D01","keep")');
assert.equal(nodes.cards.children.filter(n=>n.tag==='article').length,3);
evaluate('state.selected=-3; render()');
assert.equal(nodes.cards.children.filter(n=>n.tag==='article').length,1);
evaluate('updateItem("D01","pending")');
assert.equal(evaluate('state.selected'),-2);
assert.equal(nodes.cards.children.filter(n=>n.tag==='article').length,4);
assert.equal(evaluate('state.report.items.length'),4);
evaluate('state.selected=1; render()');
assert.equal(nodes.cards.children.filter(n=>n.tag==='article').length,4);
evaluate('setMode("review")');
assert.equal(nodes.categories.hidden,false);
assert.equal(nodes.categories.children.length,13);
console.log('PASS: no bilingual categories; direct role selection creates report; changing role/sample refreshes; review categories restored.');
evaluate('loadSample(); run()');
nodes.language.value='zh';nodes.language.onchange();
assert(nodes.categories.children[1].textContent.startsWith('一、'));
assert(nodes.categories.children[12].textContent.startsWith('十二、'));
const report=evaluate('reportText()');
assert(!report.includes('原始建议'));
assert(report.indexOf('需要确认')<report.indexOf('修改方向'));
nodes.language.value='en';nodes.language.onchange();
assert(nodes.categories.children[1].textContent.startsWith('1. '));
assert(!evaluate('reportText()').includes('Original suggestion'));
console.log('PASS: localized numbering, confirmation before approach, no duplicate original suggestion in report.');
nodes.language.value='zh';evaluate('state.selected=-1; loadSample(); run()');
const cardById=id=>nodes.cards.children.find(n=>n.id==='finding-'+id);
const buttonsFor=id=>cardById(id).children.at(-1).children[0].children;
assert.deepEqual(buttonsFor('P01').map(n=>n.textContent),['保留','不采纳','编辑建议']);
const details=cardById('P01').children.find(n=>n.tag==='details');
assert.equal(details.children.length,2);
assert.equal(details.children[1].tag,'blockquote');
assert(details.children[1].children[1].textContent.startsWith('注意：'));
buttonsFor('P01')[0].onclick();
assert.deepEqual(buttonsFor('P01').map(n=>n.textContent),['撤销']);
buttonsFor('P01')[0].onclick();
assert.deepEqual(buttonsFor('P01').map(n=>n.textContent),['保留','不采纳','编辑建议']);
evaluate('updateItem("P01","reject")');
assert.deepEqual(buttonsFor('P01').map(n=>n.textContent),['撤销']);
evaluate('updateItem("P01","pending");updateItem("P01","edited","测试修改")');
assert.deepEqual(buttonsFor('P01').map(n=>n.textContent),['撤销']);
nodes.language.value='en';nodes.language.onchange();
assert.deepEqual(buttonsFor('P01').map(n=>n.textContent),['Undo']);
console.log('PASS: inline note, action order, handled-only undo, and English undo.');
evaluate('loadSample()');assert.equal(nodes.sampleNote.hidden,false);
nodes.contract.value='自定义合同';nodes.contract.oninput();assert.equal(nodes.sampleNote.hidden,true);
evaluate('loadSample("en")');assert.equal(nodes.sampleNote.hidden,false);
nodes.clear.onclick();assert.equal(nodes.sampleNote.hidden,true);
evaluate('setMode("compare");loadSample()');
assert.equal(nodes.loadZh.textContent,'中英文合同');assert.equal(nodes.loadEn.hidden,true);
assert.equal(nodes.sampleNote.hidden,false);
nodes.secondary.value+='change';nodes.secondary.oninput();assert.equal(nodes.sampleNote.hidden,true);
evaluate('setMode("review");loadSample()');assert.equal(nodes.loadEn.hidden,false);
console.log('PASS: compact sample controls; fictional notice tracks unchanged samples; single bilingual sample entry.');
if(process.env.TEST_HTML){(async()=>{
 context.AbortSignal=AbortSignal;
 context.window.CONTRACT_LOCAL={token:'fake-local-token'};
 nodes.engine.value='ai';nodes.engine.onchange();
 nodes.role.value='buyer';evaluate('loadSample()');assert.equal(evaluate('state.report'),null);
 let calls=0;context.fetch=async()=>{calls++;throw Error('模拟网络失败')};
 await evaluate('run()');assert.equal(calls,0); // no consent
 nodes.consent.checked=true;await evaluate('run()');assert.equal(calls,1);assert.equal(evaluate('state.report'),null);assert(nodes.status.textContent.includes('不会用预设'));
 context.fetch=async()=>({ok:true,json:async()=>({report:evaluate('({...createReport("review","buyer",zhSample,"",""),items:createReport("review","buyer",zhSample,"","").items.map(f=>({...f,quotes:[],evidence:[]})),kind:"ai",coverage:[],limitations:["测试限制"],usage:null})'),remaining:18})});
 await evaluate('run()');assert.equal(evaluate('state.report.kind'),'ai');assert(evaluate('reportText()').includes('刘清清'));
 nodes.language.value='en';nodes.language.onchange();assert.equal(evaluate('state.report'),null);
 let release;context.fetch=()=>new Promise(resolve=>{release=resolve});
 const pending=evaluate('run()');assert.equal(nodes.run.disabled,true);assert.equal(nodes.engine.disabled,true);
 release({ok:false,json:async()=>({error:'模拟余额不足'})});await pending;assert.equal(nodes.run.disabled,false);
 assert.equal(nodes.cards.children[0].children[0].textContent,'本次审查未完成');
 assert(evaluate('diagnosticLines(state.failure).join(" ")').includes('Cost is unknown'));
 nodes.language.value='zh';assert(evaluate('diagnosticLines(state.failure).join(" ")').includes('无法确认'));
 context.fetch=async()=>({ok:false,json:async()=>({error:'模型达到输出上限',remaining:17,diagnostics:{code:'OUTPUT_LIMIT',finishReason:'length',httpStatus:200,maxOutputTokens:8192,usage:{input:10000,output:8192,reasoning:7000,estimatedCny:.3112}}})});
 await evaluate('run()');assert.equal(evaluate('state.failure.code'),'OUTPUT_LIMIT');
 assert(evaluate('diagnosticLines(state.failure).join(" ")').includes('7000'));
 assert(evaluate('diagnosticLines(state.failure).join(" ")').includes('0.3112'));
 assert.equal(evaluate('state.report'),null);assert.equal(nodes.export.disabled,true);
 nodes.contract.value+=' ';nodes.contract.oninput();assert.equal(evaluate('state.failure'),null);
 console.log('PASS: explicit AI consent, no auto-call on sample load, no canned fallback, signed AI export, language invalidation, and in-flight controls.');
})().catch(e=>{console.error(e);process.exitCode=1})}
